### ISSUE TITLE
`No component or dynamic content item` error after editing an email with dynamic content in GrapeJS code mode

### ISSUE THREAD

**Issue by putzwasser** [mautic/grapesjs-preset-mautic#48]
Editing an email via the code mode editor fails if you have a `Dynamic Content` element in your email.

1. Add a `Dynamic Content` block to an email
2. Open the code mode editor pane (`Edit Code`)
3. Edit some code (or don't) and click `Save`

The editor shows an alert:

> No component or dynamic content item

see this isse for further reference: https://github.com/mautic/mautic/issues/12481

The issue is in https://github.com/mautic/grapesjs-preset-mautic/blob/main/src/dynamicContent/dynamicContent.service.js#L151. `dcItem` is `undefined` when you try to save.

**Comment by LordRembo** [comment]
~~The root cause, is a condition is missing from the 'remove' event, causing the ID to be removed from storage when opening the Editor. My update PR fixes this issue.~~
~~[This is the specific code in `src/dynamicContent/dynamicContent.events.js` for reference](https://github.com/mautic/grapesjs-preset-mautic/pull/49/files#diff-72dcf97ff1eb37534d339591563791b18857e5188e0f40c9402f6f92c5195f65)~~

**Comment by LordRembo** [comment]
Never mind, was looking at the wrong issue reference.

**Comment by LordRembo** [comment]
I think this was fixed with other PR's getting merged. Can you confirm if it's resolved in 5.x?

**Comment by RCheesley** [comment]
As far as I know this is resolved but please request a re-open if not.
